= Codion World Demo

A demo application based on the Codion application framework.

== Modules

=== world-domain-api

The domain model API.

=== world-domain

The domain model implementation.

=== world-client

Swing client application.

=== world-client-http

Swing client configured with a HTTP connection.

=== world-client-local

Swing client configured with a local JDBC connection.

=== world-client-remote

Swing client configured with a remote RMI connection.

=== world-server

A Codion server configured for the World application.

=== world-server-monitor

A Codion server monitor configured to connect to the server.

== Running

=== JDBC

To run the client with a local JDBC connection.

[source,shell]
----
gradlew client-local:run
----

=== RMI

To run the client with an RMI connection start by running the server.

[source,shell]
----
gradlew server:run
----

Then run the remote client.

[source,shell]
----
gradlew client-remote:run
----

==== Server Monitor

To run the server monitor.

[source,shell]
----
gradlew server-monitor:run
----

== Server configuration

In order to run the server on a different host, you must change the *serverHost* property in *gradle.properties*.

[source,shell]
----
serverHost=192.168.1.42
----

=== jlink

The client, server and server-monitor modules have a jlink task.

[source,shell]
----
gradlew chinook-client-remote:jlink
----
[source,shell]
----
gradlew chinook-server:jlink
----
[source,shell]
----
gradlew chinook-server-monitor:jlink
----

=== jpackage

The client, server and server-monitor modules have a jpackage task configured for windows (msi) and linux (deb).

[source,shell]
----
gradlew chinook-client-remote:jpackage
----
[source,shell]
----
gradlew chinook-server:jpackage
----
[source,shell]
----
gradlew chinook-server-monitor:jpackage
----